### PR TITLE
Modify method 'add' to return newly added node. This can be used to add ...

### PR DESCRIPTION
**Pull request by boldo**
...a payload to the node, e.g. tree.add(point).payload = 42. The payload can then be retrieved, e.g. print tree.search_nn(query).payload.

### CODE REVIEW

**Comment by stefankoegl** [comment]
Thanks for your pull request!

Could you please add a test that verifies the changed behaviour? I understand that the change is quite simple, but a test would ensure that the functionality is not accidentally removed or changed later on.

**Comment by boldo** [comment]
Test added.

**Comment by stefankoegl** [comment]
Thanks!

**Comment by stefankoegl** [comment]
I've just released [0.12](https://github.com/stefankoegl/kdtree/releases/tag/v0.12) which contains your changes.

**Pull request merged**
